wordpress:
    build: ./php-wordpress
    links:
      - db:mysql
    expose: 
      - "9000"
    volumes:
      - /var/www/html:/var/www/html
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password

db:
  image: mysql:latest
  expose:
    - "3306"
  ports:
    - "3306:3306"
  volumes:
    - /home/user/mysql_volume:/var/lib/mysql
    - ./volume/log/mysqld.log:/var/log/mysqld.log
  environment:
    MYSQL_ROOT_PASSWORD: example

httpserver:
  image: nginx
  ports:
    - "80:80"
  links:
    - wordpress
  volumes:
    - ./volume/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./volume/nginx/conf.d/:/etc/nginx/conf.d/
    - ./volume/log/nginx:/var/log/nginx
    - /var/www/html:/var/www/html